package com.ttasm.manager.dao;

import com.ttasm.manager.pojo.Train_Number;

import java.util.List;

public interface Train_NumberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table train_number
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String trainNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table train_number
     *
     * @mbg.generated
     */
    int insert(Train_Number row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table train_number
     *
     * @mbg.generated
     */
    Train_Number selectByPrimaryKey(String trainNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table train_number
     *
     * @mbg.generated
     */
    List<Train_Number> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table train_number
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Train_Number row);
}