package com.ttasm.manager.dao;

import com.ttasm.manager.pojo.Train;

import java.util.List;

public interface TrainMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table train
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String trainId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table train
     *
     * @mbg.generated
     */
    int insert(Train row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table train
     *
     * @mbg.generated
     */
    Train selectByPrimaryKey(String trainId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table train
     *
     * @mbg.generated
     */
    List<Train> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table train
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Train row);
}