package com.ttasm.manager.dao;

import com.ttasm.manager.pojo.Tricket;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
@Mapper

public interface TricketMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tricket
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String ticketId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tricket
     *
     * @mbg.generated
     */
    int insert(Tricket row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tricket
     *
     * @mbg.generated
     */
    Tricket selectByPrimaryKey(String ticketId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tricket
     *
     * @mbg.generated
     */
    List<Tricket> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tricket
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Tricket row);
}