package com.ttasm.manager.pojo;

public class Train_Number {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column train_number.train_number
     *
     * @mbg.generated
     */
    private String trainNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column train_number.train_ID
     *
     * @mbg.generated
     */
    private String trainId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column train_number.starting_time
     *
     * @mbg.generated
     */
    private String startingTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column train_number.price
     *
     * @mbg.generated
     */
    private Integer price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column train_number.starting_station
     *
     * @mbg.generated
     */
    private String startingStation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column train_number.ending_station
     *
     * @mbg.generated
     */
    private String endingStation;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column train_number.train_number
     *
     * @return the value of train_number.train_number
     *
     * @mbg.generated
     */
    public String getTrainNumber() {
        return trainNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column train_number.train_number
     *
     * @param trainNumber the value for train_number.train_number
     *
     * @mbg.generated
     */
    public void setTrainNumber(String trainNumber) {
        this.trainNumber = trainNumber == null ? null : trainNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column train_number.train_ID
     *
     * @return the value of train_number.train_ID
     *
     * @mbg.generated
     */
    public String getTrainId() {
        return trainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column train_number.train_ID
     *
     * @param trainId the value for train_number.train_ID
     *
     * @mbg.generated
     */
    public void setTrainId(String trainId) {
        this.trainId = trainId == null ? null : trainId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column train_number.starting_time
     *
     * @return the value of train_number.starting_time
     *
     * @mbg.generated
     */
    public String getStartingTime() {
        return startingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column train_number.starting_time
     *
     * @param startingTime the value for train_number.starting_time
     *
     * @mbg.generated
     */
    public void setStartingTime(String startingTime) {
        this.startingTime = startingTime == null ? null : startingTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column train_number.price
     *
     * @return the value of train_number.price
     *
     * @mbg.generated
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column train_number.price
     *
     * @param price the value for train_number.price
     *
     * @mbg.generated
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column train_number.starting_station
     *
     * @return the value of train_number.starting_station
     *
     * @mbg.generated
     */
    public String getStartingStation() {
        return startingStation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column train_number.starting_station
     *
     * @param startingStation the value for train_number.starting_station
     *
     * @mbg.generated
     */
    public void setStartingStation(String startingStation) {
        this.startingStation = startingStation == null ? null : startingStation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column train_number.ending_station
     *
     * @return the value of train_number.ending_station
     *
     * @mbg.generated
     */
    public String getEndingStation() {
        return endingStation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column train_number.ending_station
     *
     * @param endingStation the value for train_number.ending_station
     *
     * @mbg.generated
     */
    public void setEndingStation(String endingStation) {
        this.endingStation = endingStation == null ? null : endingStation.trim();
    }
}