package com.ttasm.manager.pojo;

public class Tricket {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tricket.ticket_ID
     *
     * @mbg.generated
     */
    private String ticketId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tricket.train_number
     *
     * @mbg.generated
     */
    private String trainNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tricket.seat
     *
     * @mbg.generated
     */
    private String seat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tricket.ticket_ID
     *
     * @return the value of tricket.ticket_ID
     *
     * @mbg.generated
     */
    public String getTicketId() {
        return ticketId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tricket.ticket_ID
     *
     * @param ticketId the value for tricket.ticket_ID
     *
     * @mbg.generated
     */
    public void setTicketId(String ticketId) {
        this.ticketId = ticketId == null ? null : ticketId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tricket.train_number
     *
     * @return the value of tricket.train_number
     *
     * @mbg.generated
     */
    public String getTrainNumber() {
        return trainNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tricket.train_number
     *
     * @param trainNumber the value for tricket.train_number
     *
     * @mbg.generated
     */
    public void setTrainNumber(String trainNumber) {
        this.trainNumber = trainNumber == null ? null : trainNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tricket.seat
     *
     * @return the value of tricket.seat
     *
     * @mbg.generated
     */
    public String getSeat() {
        return seat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tricket.seat
     *
     * @param seat the value for tricket.seat
     *
     * @mbg.generated
     */
    public void setSeat(String seat) {
        this.seat = seat == null ? null : seat.trim();
    }
}